import assert from 'node:assert/strict';
import fs from 'fs';
import path from 'path';
import YAML from 'yaml';

const workflowPath = path.resolve(process.cwd(), '..', '.github', 'workflows', 'doordash-weekly-production.yml');
const validationPath = path.resolve(process.cwd(), '..', '.github', 'workflows', 'doordash-weekly-validation.yml');

const workflow = YAML.parse(fs.readFileSync(workflowPath, 'utf8')) as any;
const validation = YAML.parse(fs.readFileSync(validationPath, 'utf8')) as any;
const productionSteps = workflow.jobs['weekly-production'].steps as any[];
const validationSteps = validation.jobs.validate.steps as any[];
const productionRunStep = productionSteps.find((step: any) => step.id === 'workflow_run');
const validationServices = validation.jobs.validate.services;
const stepByName = (steps: any[], name: string) => steps.find((step: any) => step.name === name);

assert.equal(workflow.on.schedule[0].cron, '5 18 * * 0');
assert.ok(workflow.on.workflow_dispatch);
assert.equal(workflow.on.workflow_dispatch.inputs.run_mode.default, 'preflight');
assert.deepEqual(workflow.on.workflow_dispatch.inputs.run_mode.options, ['preflight', 'full']);
assert.equal(workflow.jobs['weekly-production']['runs-on'], 'ubuntu-latest');
assert.equal(workflow.jobs['weekly-production']['timeout-minutes'], 30);
assert.equal(workflow.jobs['weekly-production'].outputs.failure_summary, '${{ steps.workflow_run.outputs.failure_summary }}');
assert.equal(workflow.concurrency['cancel-in-progress'], false);
assert.equal(workflow.permissions.contents, 'read');
assert.equal(workflow.jobs['weekly-production'].permissions.contents, 'read');
assert.equal(workflow.jobs['create-production-issue'].permissions.issues, 'write');
assert.equal(productionSteps[0].uses, 'actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09');
assert.equal(productionSteps[1].uses, 'actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444');
assert.ok(productionSteps.some((step: any) => step.uses === 'actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02'));
assert.equal(workflow.jobs['create-production-issue'].steps[0].uses, 'actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd');
assert.equal(productionSteps.find((step: any) => step.name === 'Install dependencies').run.trim(), 'npm ci');
assert.equal(stepByName(productionSteps, 'Validate production store config').run.trim(), 'npm run validate:production-store-config');
assert.equal(stepByName(productionSteps, 'Test weekly window').run.trim(), 'npm run test:weekly-window');
assert.equal(stepByName(productionSteps, 'Test production sanitization').run.trim(), 'npm run test:production-sanitization');
assert.equal(stepByName(productionSteps, 'Test production storage').run.trim(), 'npm run test:production-storage');
assert.equal(stepByName(productionSteps, 'Test production OpenAI provider').run.trim(), 'npm run test:production-openai');
assert.equal(stepByName(productionSteps, 'Test production ingestion').run.trim(), 'npm run test:production-ingestion');
assert.equal(stepByName(productionSteps, 'Test production Postgres').run.trim(), 'npm run test:production-postgres');
assert.equal(stepByName(productionSteps, 'Test production runner').run.trim(), 'npm run test:production-runner');
assert.equal(stepByName(productionSteps, 'Validate workflow definitions').run.trim(), 'npm run test:workflow-validation');
assert.equal(stepByName(productionSteps, 'Run production preflight').run.includes('npm run preflight:production'), true);
assert.equal(productionRunStep.if, "github.event_name != 'workflow_dispatch' || inputs.run_mode == 'full'");
assert.equal(productionRunStep.env.OPENAI_MODEL, '${{ vars.OPENAI_MODEL }}');
assert.equal(productionRunStep.env.DD_REPORT_ALLOWED_SENDERS, '${{ vars.DD_REPORT_ALLOWED_SENDERS }}');
assert.equal(productionRunStep.env.IMAP_HOST, '${{ vars.IMAP_HOST }}');
assert.equal(productionRunStep.env.IMAP_PORT, '${{ vars.IMAP_PORT }}');
assert.equal(productionRunStep.env.IMAP_SECURE, '${{ vars.IMAP_SECURE }}');
assert.equal(productionRunStep.env.DD_REPORT_INBOX_LABEL, '${{ vars.DD_REPORT_INBOX_LABEL }}');
assert.equal(productionRunStep.env.OPENAI_API_KEY, '${{ secrets.OPENAI_API_KEY }}');
assert.equal(productionRunStep.env.DATABASE_URL, '${{ secrets.DOORDASH_PRODUCTION_DATABASE_URL }}');
assert.equal(productionRunStep.env.IMAP_USER, '${{ secrets.IMAP_USER }}');
assert.equal(productionRunStep.env.IMAP_PASS, '${{ secrets.IMAP_PASS }}');
assert.ok(workflow.jobs['create-production-issue'].steps[0].env.FAILURE_SUMMARY);
assert.equal(workflow.jobs['create-production-issue'].if, "${{ always() && needs.weekly-production.result == 'failure' && needs.weekly-production.outputs.pending_external_data != 'true' && (github.event_name != 'workflow_dispatch' || inputs.run_mode == 'full') }}");

assert.equal(validation.jobs.validate['runs-on'], 'ubuntu-latest');
assert.ok(validation.on.pull_request);
assert.ok(validation.on.push);
assert.equal(validation.jobs.validate.env.DD_STORAGE_BACKEND, 'postgres');
assert.equal(validation.jobs.validate.env.DATABASE_URL, 'postgres://validator:validator_password@127.0.0.1:5432/doordash_validation');
assert.equal(validationServices.postgres.image, 'postgres:16-alpine');
assert.equal(validationServices.postgres.env.POSTGRES_DB, 'doordash_validation');
assert.equal(validationServices.postgres.env.POSTGRES_USER, 'validator');
assert.equal(validationServices.postgres.env.POSTGRES_PASSWORD, 'validator_password');
assert.equal(validationSteps[0].uses, 'actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09');
assert.equal(validationSteps[1].uses, 'actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444');
assert.equal(validationSteps.find((step: any) => step.name === 'Install dependencies').run.trim(), 'npm ci');
assert.equal(stepByName(validationSteps, 'Build').run.trim(), 'npm run build');
assert.equal(stepByName(validationSteps, 'Validate production store config').run.trim(), 'npm run validate:production-store-config');
assert.equal(stepByName(validationSteps, 'Test weekly window').run.trim(), 'npm run test:weekly-window');
assert.equal(stepByName(validationSteps, 'Test production sanitization').run.trim(), 'npm run test:production-sanitization');
assert.equal(stepByName(validationSteps, 'Test production storage').run.trim(), 'npm run test:production-storage');
assert.equal(stepByName(validationSteps, 'Test production OpenAI provider').run.trim(), 'npm run test:production-openai');
assert.equal(stepByName(validationSteps, 'Test production ingestion').run.trim(), 'npm run test:production-ingestion');
assert.equal(stepByName(validationSteps, 'Test production Postgres').run.trim(), 'npm run test:production-postgres');
assert.equal(stepByName(validationSteps, 'Test production runner').run.trim(), 'npm run test:production-runner');
assert.equal(stepByName(validationSteps, 'Validate workflow definitions').run.trim(), 'npm run test:workflow-validation');

console.log('workflow-validation tests passed');
